repo: "call-to-action-banner"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - google-fonts
  - box-sizing
  - body-margin-0
  - img-flex

html:
  - path: "index.html"
    outline: false
    has:
      - ['link[href*="Roboto"]', 'The Google Font, `Roboto` (regular & bold) is missing']
      - ['link[href*="Roboto+Condensed"]', 'The Google Font, `Roboto Condensed` (bold) is missing']
      - ".banner"
      - ".banner .img-flex"
      - ".banner h2"
      - ".banner p"
      - ".banner img"
    search:
      - "Ultra Super Fighting Force"
      - "Control giant, fighting, transforming robots and save the world!"
      - "Join USFF"

css:
  - path: "css/main.css"
    has:
      - ['.banner']
      - ['.btn']
      - ['.btn:hover']
      - ['.btn-big']
    search:
      - "Roboto"
      - "Roboto Condensed"
      - "position: relative"
      - "position: absolute"
      - "float: left"
      - "float: right"
      - "left:"
      - "top:"
      - "translate"
      - "overflow: hidden"
      - "max-height"

screenshots:
  - path: "index.html"
    sizes:
      650: 10
      1400: 5

functionality:
  - path: 'index.html'
    test: |
      const btn = $('.btn')
      const oldBg = css(btn).backgroundColor;

      hover(btn, () => {
        if(oldBg == css(btn).backgroundColor) return fail('The background colour of the button doesn’t change when hovered');
        pass();
      });
