repo: "call-to-action-banner"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ['link[href*="Roboto:400,700"]', 'The Google Font, `Roboto` (regular & bold) is missing']
      - ['link[href*="Roboto+Condensed:700"]', 'The Google Font, `Roboto Condensed` (bold) is missing']
      - ".banner"
      - ".banner .img-flex"
      - ".banner h2"
      - ".banner p"
      - ".banner img"
    search:
      - "Ultra Super Fighting Force"
      - "Control giant, fighting, transforming robots and save the world!"
      - "Join USFF"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', 0]
      - ['.img-flex', 'display', 'block']
      - ['.img-flex', 'width', '100%']
      - ['.banner']
      - ['.btn']
      - ['.btn:hover']
      - ['.btn-big']
    search:
      - "Roboto"
      - "Roboto Condensed"
      - "position: relative"
      - "position: absolute"
      - "float: left"
      - "float: right"
      - "left:"
      - "top:"
      - "translate"
      - "overflow: hidden"
      - "max-height"

screenshots:
  - path: "index.html"
    sizes: [650, 1400]
